### ISSUE TITLE
Should ipsum() also have a collapse arg?

### ISSUE THREAD

**Issue by cpsievert** [gadenbuie/lorem#5]
`ipsum_words()` already does

**Comment by gadenbuie** [comment]
After #8 I've decided it's a little more trouble than it's worth, but I added a `format()` method that will turn the ipsum text into a collapsed scalar string.

``` r
lipsum <- lorem::ipsum(2, 1)
lipsum
```

> Consectetur turpis eu lacinia tristique sociis platea egestas ullamcorper molestie sollicitudin turpis purus?
> 
> Lorem venenatis egestas praesent venenatis sodales feugiat eleifend cum tristique augue.

``` r
format(lipsum)
#> [1] "Consectetur turpis eu lacinia tristique sociis platea egestas ullamcorper molestie sollicitudin turpis purus?\n\nLorem venenatis egestas praesent venenatis sodales feugiat eleifend cum tristique augue."
```
